simplesite/simpleapp/urls.py
from django.urls import path
from . import views

app_name = 'simpleapp'
urlpatterns = [
                path('',views.IndexView.as_view(),name='index'),
                path('<int:pk>/',views.DetailView.as_view(),name='detail'),
                path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
                path('<int:question_id>/vote/',views.vote,name='vote')
              ]

simplesite/simplesite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('simpleapp/',include('simpleapp.urls')),
    path('admin/', admin.site.urls)
]

simplesite/simpleapp/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

simplesite/simpleapp/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
  template_name = 'simpleapp/index.html'
  context_object_name = 'q'

  def get_queryset(self):
    return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'simpleapp/detail.html'

    def get_queryset(self):
      return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'simpleapp/detail.html'


def get_queryset(self):

  return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('simpleapp/index.html')
    context = {
                'latest_question_list':latest_question_list,
              }
    return render(request,'simpleapp/index.html',context)

def detail(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'simpleapp/detail.html',
                 {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request, 'simpleapp,results.html',{'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
      selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
      return render(request,'simpleapp/detail.html',
      {'question': question,
       'error_message': "You didn't select a choice",
       })
    else:
      selected_choice.votes += 1
      selected_choice.save()

      return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

simplesite/simpleapp/templates/simpleapp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'simpleapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

simplesite/simpleapp/templates/simpleapp/index.html
{% load static %}


{{questions}} - question

<li><a href="">{{ question.question_text }}</a></li>


<link rel="stylesheet" type="text/css" href="{% static 'simpleapp/style.css' %}">


{% for question in questions %}

<li><a href="{% url 'simpleapp:detail' question.id %}">{{ question.question_text }}</a></li>

{% endfor %}

simplesite/simpleapp/templates/simpleapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'simpleapp:detail' question.id %}">Vote again?</a>